data_guest: "examples/data/breast_hetero_mini_guest.csv"
data_host: "examples/data/breast_hetero_mini_host.csv"
idx: "id"
label_name: "y"
loss: "binary_crossentropy"
learning_rate: 0.15
tol: 0.01
batch_size: 64
metrics: ["auc", "ks"]
epochs: 2
bottom_layer_units: 2
interactive_layer_units: 2
top_layer_units: 1
guest_table_name: "breast_hetero_mini_guest"
host_table_name: "breast_hetero_mini_host"
top_act: "sigmoid"
opt: "SGD"
shape1: 3   # number of features from guest dataset
shape2: 3   # number of features from host dataset
seed: 4981